{% set name = "impact-z" %}
{% set version = "2.7.4" %}

{% set build = 0 %}
# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'openmpi' %}
# prioritize OpenMPI variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/impact-lbl/IMPACT-Z/archive/refs/tags/V{{ version }}.tar.gz
  sha256: c4ac59756fd0ddc8d6e2310a9868d122c8476cf29ce94c390067be7c0c8fbfe3

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != 'nompi' %}

  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - make
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - cmake
    - openmpi  # [mpi == "openmpi" and (build_platform != target_platform)]
  host:
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - {{ mpi }}  # [mpi != 'nompi']

test:
  commands:
    - which ImpactZexe  # [unix]
    - which ImpactZexe-mpi  # [unix and mpi != 'nompi']
    - where ImpactZexe  # [win]

about:
  home: https://github.com/impact-lbl/IMPACT-Z
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: license.txt
  summary: IMPACT-Z - Integrated Map and Particle ACcelerator Tracking Code
  description: |
    IMPACT-Z is a parallel+serial particle-in-cell code whose primary purpose
    is to model the dynamics of multiple charged particle beams in linear and
    ring accelerators. The code uses longitudinal position (z) as independent
    variable and includes the effects of externally applied fields from magnets
    and accelerating cavities as well as the effect of self-fields (space
    charge fields).
  doc_url: https://amac.lbl.gov/~jiqiang/IMPACT/index.html
  dev_url: https://github.com/impact-lbl/IMPACT-Z

extra:
  recipe-maintainers:
    - ken-lauer
    - hhslepicka
    - ChristopherMayes
